# Spring Boot 基础配置
spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.222.138.172:3306/mybatis_plus_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: jFLA6LkGF6LjRJbK

# Mybatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml # MyBatis-Plus XML 映射文件位置
  type-aliases-package: com.xm.demo01.entity # 实体类包路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启 SQL 日志打印